### ISSUE TITLE
ModuleNotFoundError: No module named 'medacy.ner' 

### ISSUE THREAD

**Issue by SaumitraChaskar** [NLPatVCU/medaCy#168]
#### Description

while installing medaCy_model_clinical_notes, the following error is thrown,

    Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Saumitra\AppData\Local\Temp\pip-req-build-td8r2nuh\setup.py", line 3, in <module>
        from medacy_model_clinical_notes import __version__, __authors__
      File "C:\Users\Saumitra\AppData\Local\Temp\pip-req-build-td8r2nuh\medacy_model_clinical_notes\__init__.py", line 1, in <module>
        from .medacy_model_clinical_notes import load
      File "C:\Users\Saumitra\AppData\Local\Temp\pip-req-build-td8r2nuh\medacy_model_clinical_notes\medacy_model_clinical_notes.py", line 3, in <module>
        from medacy.ner.pipelines import ClinicalPipeline
    **ModuleNotFoundError: No module named 'medacy.ner'**

#### Steps/Code to Reproduce
running pip install git+https://github.com/NLPatVCU/medaCy_model_clinical_notes.git

#### Versions

Platform : Windows-10-10.0.18362-SP0
Python : Python  3.6.8 |Anaconda, Inc.| (default, Feb 21 2019, 18:30:04) [MSC v.1916 64 bit (AMD64)]
Numpy : Numpy  1.17.4
Scipy : Scipy  1.3.1
Medacy : medacy  0.2.0

I have installed medaCy through the development branch.

Is the medaCy.ner module to be downloaded and installed seperately.

**Comment by swfarnsworth** [comment]
Hello, thanks for getting in touch with us. I see that you're using an older version of medaCy, which is incompatible with the current version of the model. Is there a reason you need to use the older version of medaCy? Otherwise, please make sure you're using the latest version of the master branch of both packages.

If you encounter any other issues, it would be very helpful for us to know.

**Comment by SaumitraChaskar** [comment]
After using the command "pip install git+https://github.com/NLPatVCU/medaCy.git" the version of medaCy getting installed is 0.2.0.

from where to get the latest version ?

**Comment by swfarnsworth** [comment]
Please run this command: `pip install git+https://github.com/NLPatVCU/medaCy_model_clinical_notes.git`

This should install the most recent version of the model package. If you still encounter any errors, they should be resolved by the time we release the next version of medaCy, which I hope to do as soon as possible.

**Comment by swfarnsworth** [comment]
I just discovered an error and pushed up a fix. If you install the model again using the command from my previous message, I have confirmed that it will work. Thank you for your patience and don't hesitate to let us know about any other errors you encounter.

**Comment by SaumitraChaskar** [comment]
Thank you ! , The model was successfully installed and the results were just as expected.

**Comment by bbardakk** [comment]
Even running command that you mention in your command @swfarnsworth , when I try to run this line 
`model = Model.load_external('medacy_model_clinical_notes')`
I took an error message like below:

```
from medacy.ner.pipelines import ClinicalPipeline
ModuleNotFoundError: No module named 'medacy.ner'
```

**Comment by swfarnsworth** [comment]
@bbardakk, this commit shows that I changed the line that is causing that error: https://github.com/NLPatVCU/medaCy_model_clinical_notes/commit/1f546ddb2db3419789cfd6b4d34ed050e001364b#diff-5dec9c8f301d93a3ef91ab073d6a9115

If the version being installed by the command I specified does not contain that commit, try cloning the repository and installing it.

```
git clone https://github.com/NLPatVCU/medaCy_model_clinical_notes.git
cd medaCy_model_clinical_notes
pip install -e .
```

**Comment by swfarnsworth** [comment]
Greetings, today I updated the clinical notes model to use a different tokenzier that has been demonstrated to be more performant. I hope that this will increase the accuracy and usefulness of your results. Please let me know if you encounter any issues.

**Comment by brendancopeunmc** [comment]
Greetings.  Today I received this error:

Complete output (9 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\downloads\medaCy_model_clinical_notes\setup.py", line 3, in <module>
        from medacy_model_clinical_notes import __version__, __authors__
      File "C:\downloads\medaCy_model_clinical_notes\medacy_model_clinical_notes\__init__.py", line 1, in <module>
        from .medacy_model_clinical_notes import load
      File "C:\downloads\medaCy_model_clinical_notes\medacy_model_clinical_notes\medacy_model_clinical_notes.py", line 9, in <module>
        from medacy.pipeline_components.learners.crf_learner import get_crf
    ModuleNotFoundError: No module named 'medacy.pipeline_components.learners.crf_learner'

**Comment by swfarnsworth** [comment]
@brendancopeunmc, please install the development branch for now. We'll be releasing a new version to master very soon and going forward our transitions between versions will be much smoother.

`pip install git+https://github.com/NLPatVCU/medaCy.git@development`

**Comment by sherwin7** [comment]
this issued is solved thanks for solving it @swfarnsworth 
please make it available in the master branch as soon as possible thanks

**Comment by flaviofuka** [comment]
installing medaCy from development branch and then installing medaCy_model_clinical_notes worked!!

Thanks

**Comment by swfarnsworth** [comment]
Thank you everyone for uncovering these errors. I'm going to try to release to master today. Please let me know if you discover any other errors.

**Comment by Jessie-cm-lee** [comment]
Hi, I have same issue and I followed all the directions mentioned above, but still occurring same error code. I was trying to open medaCy_demo:

Error: % python app.py
Traceback (most recent call last):
  File "app.py", line 2, in <module>
    from medacy.ner import Model
ModuleNotFoundError: No module named 'medacy.ner'

Platform : Mac OSX 10.15.4 Catalina
Python 3.8.3
Numpy 1.18.4
Scipy 1.4.1
SpaCy 2.2.2
Medacy 1.0.0

Also, I've looked at the document https://medacy.readthedocs.io/en/latest/medacy.ner.model.html but it was empty.

**Comment by swfarnsworth** [comment]
There was a new release today. Please open a new issue if you experience this or any other issue going forward.
